pipeline {
    agent { label 'agent1' }  // Specify the Jenkins node label here

    environment {
        REPO_URL = 'https://github.com/lherbeng/RKE2.git' // Replace with your actual repo
        SCRIPT_PATH = 'rancher/install_rke2_server.sh'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
                git url: "${REPO_URL}", branch: 'main'
            }
        }

        stage('Install RKE2 Server') {
            steps {
                // Provide execution permission to the script
                sh 'chmod +x ${SCRIPT_PATH}'
                
                // Run the script
                sh "./${SCRIPT_PATH}"
            }
        }

        stage('Verify RKE2 Installation') {
            steps {
                // Verify that RKE2 server is running and kubectl is working
                sh 'kubectl get node -o wide || echo "kubectl not found or RKE2 server is not running."'
            }
        }
    }

    post {
        success {
            echo 'RKE2 Server installed successfully!'
        }
        failure {
            echo 'RKE2 Server installation failed.'
        }
    }
}
